export { default as Hero } from "./Hero"
export { default as Porque } from "./Porque"
export { default as Section } from "./Section"
export { default as Title } from "./Title"
export { default as List } from "./List"
export { default as ItemList } from "./ItemList"
export { default as Source } from "./Source"
export { default as Como } from "./Como"